// Define fuera del handler para reutil
const COLUMN_CONFIG_INV = [
    { key: 'bienid',           header: 'Número',              width: 9999, nullText: ''},
    { key: 'imagenurl',        header: 'Imagen',              width: 9999, nullText: 'Sin imagen'},
    { key: 'codigodepartida',  header: 'Código',              width: 9999, nullText: ''},
    { key: 'fecha_alta',       header: 'Fecha alta',          width: 9999, nullText: 'Sin fecha' },
    { key: 'descripcion',      header: 'Descripción',         width: 9999, nullText: 'Sin descripción' },
    { key: 'cantidad',         header: 'Cantidad',            width: 9999, nullText: '0' },
    { key: 'marca',            header: 'Marca',               width: 9999, nullText: '0'},
    { key: 'modelo',           header: 'Modelo',              width: 9999, nullText: '0'},
    { key: 'numeroserie',      header: 'Serie',               width: 9999, nullText: 'N/A'},
    { key: 'num_inventario',   header: 'No. de inventario',   width: 9999, nullText: 'Sin inventario' },
    { key: 'nombre_persona',   header: 'Nombre de la persona',width: 9999, nullText: ''},
    { key: 'depcuenta',        header: 'Nombre de la cuenta', width: 9999, nullText: ''},
    { key: 'cuenta',           header: 'Cuenta dep.',         width: 9999, nullText: ''},
    { key: 'fechaadquision',   header: 'Fecha Adq.',          width: 9999, nullText: ''},
    { key: 'cotizacion',       header: 'Valor Cotización',    width: 9999, nullText: ''},
    { key: 'costoadquision',   header: 'Costo Adq.',          width: 9999, nullText: '' },
    { key: 'vidautil',         header: 'Años de vida útil',   width: 9999, nullText: ''},
    { key: 'estado',           header: 'Estatus',             width: 9999, nullText: 'No definido' },
    { key: 'lugar',            header: 'Ubicación',           width: 9999, nullText: 'Sin ubicación' },
    { key: 'donativo',         header: '¿Es Donativo?',       width: 9999, nullText: 'No', transform: v => v ? 'Sí' : 'No' },
    { key: 'observaciones',    header: 'Observaciones',       width: 9999, nullText: '' },
    { key: 'despreciacion',    header: 'Despreciación',       width: 9999, nullText: '' },
    { key: 'valorlibros',      header: 'Valor en libros',     width: 9999, nullText: '' },
    { key: 'fecharesguardo',   header: 'Fecha de resguardo',  width: 9999, nullText: 'No aplica' },
    { key: 'motivoresguardo',  header: 'Motivo de resguardo', width: 9999, nullText: 'No aplica' },
    { key: 'fechabaja',        header: 'Fecha de baja',       width: 9999, nullText: 'No aplica' },
    { key: 'tipobaja',         header: 'Tipo de baja',        width: 9999, nullText: 'No aplica' },
    { key: 'documentobaja',    header: 'Documento de baja',   width: 9999, nullText: 'No aplica' },
    { key: 'fechapoliza',      header: 'Fecha de poliza',     width: 9999, nullText: 'No aplica' },
    { key: 'fechadocumentopoliza', header: 'Fecha del documento de poliza', width: 9999, nullText: 'No aplica' },
    { key: 'documentopoliza:', header: 'Documento de poliza', width: 9999, nullText: 'No aplica' },
];